# Generated by Django 4.1.6 on 2023-02-05 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait_photo', models.FileField(blank=True, null=True, upload_to='users/PortraitPhotos')),
                ('national_id', models.FileField(blank=True, null=True, upload_to='users/NationalIds')),
                ('passport', models.FileField(blank=True, null=True, upload_to='users/Passports')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='users/DrivingLicense')),
                ('tax_payer_registration', models.FileField(blank=True, null=True, upload_to='users/TPIN')),
                ('g7_results', models.FileField(blank=True, null=True, upload_to='users/G7Results')),
                ('g9_results', models.FileField(blank=True, null=True, upload_to='users/G9Results')),
                ('g12_results', models.FileField(blank=True, null=True, upload_to='users/G12Results')),
                ('school_diploma', models.FileField(blank=True, null=True, upload_to='users/SchoolDiplomas')),
                ('school_degree', models.FileField(blank=True, null=True, upload_to='users/SchoolDegree')),
                ('school_masters', models.FileField(blank=True, null=True, upload_to='users/users/SchoolMasters')),
                ('school_phd', models.FileField(blank=True, null=True, upload_to='users/SchoolPHD')),
                ('proof_of_residence', models.FileField(blank=True, null=True, upload_to='users/ResidenceProof')),
                ('resume', models.FileField(blank=True, null=True, upload_to='users/Resumes')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='users/MedicalCertificates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Documents',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('country_of_birth', models.CharField(max_length=255)),
                ('town_of_birth', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('current_occupation', models.CharField(max_length=255)),
                ('is_minor', models.BooleanField(default=False)),
                ('primary_phone', models.CharField(max_length=255)),
                ('secondary_phone', models.CharField(max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_profile_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_profile_link', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedIn_profile_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_handle', models.CharField(max_length=255)),
                ('youtube_channel_link', models.URLField(blank=True, max_length=255, null=True)),
                ('residential_address', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_address', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(max_length=255)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('year_completed_g7', models.IntegerField(blank=True, null=True)),
                ('year_completed_g9', models.IntegerField(blank=True, null=True)),
                ('year_completed_g12', models.IntegerField(blank=True, null=True)),
                ('year_completed_diploma', models.IntegerField(blank=True, null=True)),
                ('year_completed_degree', models.IntegerField(blank=True, null=True)),
                ('year_completed_masters', models.IntegerField(blank=True, null=True)),
                ('year_completed_phd', models.IntegerField(blank=True, null=True)),
                ('marks_obtained_g7', models.IntegerField(blank=True, null=True)),
                ('marks_obtained_g9', models.IntegerField(blank=True, null=True)),
                ('points_obtained_g12', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.BinaryField(unique=True)),
                ('face', models.BinaryField(blank=True, null=True, unique=True)),
                ('iris', models.BinaryField(blank=True, null=True, unique=True)),
                ('voice', models.BinaryField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Biometrics',
            },
        ),
    ]
