# Generated by Django 4.1.6 on 2023-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
