# Generated by Django 4.1.6 on 2023-02-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdetails_secondary_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='middle_name',
        ),
    ]
