# Generated by Django 4.1.7 on 2023-03-11 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0007_otheruserdocument_otheruserdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalIdentityCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=50)),
                ("mother_or_father_place_of_bith", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("chief", models.CharField(max_length=255)),
                ("village", models.CharField(max_length=255)),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
