# Generated by Django 4.1.7 on 2023-03-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_type_usertransaction_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="chief",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="district",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="mother_or_father_place_of_bith",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="digitalidentitycard",
            name="village",
        ),
    ]
