# Generated by Django 4.1.7 on 2023-03-11 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0010_remove_digitalidentitycard_chief_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalidentitycard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
