# Generated by Django 4.1.7 on 2023-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_digitalidentitycard_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biometrics",
            name="fingerprint",
            field=models.BinaryField(blank=True, null=True, unique=True),
        ),
    ]
