# Generated by Django 4.1.7 on 2023-04-09 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAgencyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_government", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherCorporateAgencyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail_key", models.CharField(max_length=100)),
                ("details_value", models.CharField(max_length=100)),
                (
                    "corporate_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.corporateagencydetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateAgencyWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "maximum_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "corporate_agency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.corporateagencydetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateAgencyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_type", models.CharField(max_length=100)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "corporate_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.corporateagencydetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateAgencyDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_name", models.CharField(max_length=100)),
                (
                    "document_file",
                    models.FileField(upload_to="corporate_agency_documents/"),
                ),
                (
                    "corporate_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.corporateagencydetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorporateAgencyBiometrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.BinaryField(blank=True, null=True, unique=True)),
                ("face", models.BinaryField(blank=True, null=True, unique=True)),
                ("iris", models.BinaryField(blank=True, null=True, unique=True)),
                ("voice", models.BinaryField(blank=True, null=True, unique=True)),
                (
                    "corporate_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.corporateagencydetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
