# Generated by Django 4.1.6 on 2023-02-05 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('tax_payer_number', models.CharField(max_length=20)),
                ('institution_type', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=64)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorporation_certificate', models.FileField(upload_to='business/IncorporationCertificates')),
                ('tax_payer_identification', models.FileField(upload_to='institution/tpin')),
                ('profile', models.FileField(upload_to='institution/profile')),
                ('articles_of_association', models.FileField(upload_to='institution/Articles')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.institution')),
            ],
        ),
    ]
