# Generated by Django 4.1.7 on 2023-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_business_businessdocuments_businesswallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otherbusinessdocuments",
            name="description",
            field=models.TextField(default="..."),
            preserve_default=False,
        ),
    ]
