# Generated by Django 4.1.7 on 2023-03-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_otherbusinessdocuments_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time_created", models.DateTimeField(auto_now_add=True)),
                ("transaction_type", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
