# Generated by Django 4.1.7 on 2023-03-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.business",
            ),
            preserve_default=False,
        ),
    ]
