# Generated by Django 4.1.7 on 2023-03-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0005_transaction_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessBiometrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.BinaryField(blank=True, null=True, unique=True)),
                ("face", models.BinaryField(blank=True, null=True, unique=True)),
                ("iris", models.BinaryField(blank=True, null=True, unique=True)),
                ("voice", models.BinaryField(blank=True, null=True, unique=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
